sudo: required
language: php
dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.travis .env
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit tests/Unit/PackageTestCases.php
  - vendor/bin/phpunit tests/Browser/BrowserTestCases.php
